version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-actions-version-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      uv-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      uv-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
    commit-message:
      prefix: "build"
