changelog:
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Maintainance
      labels:
        - maintainance
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
