changelog:
  categories:
    - title: Breaking
      labels:
        - breaking
    - title: Deprecation
      labels:
        - deprecation
    - title: Enhancements
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
