# -*- coding: utf-8 -*-
# Auto-generated by schemapi: do not modify file directly
# - schemapi version: 0.3.0.dev0+791c7f6
# - date:    2017-08-11 11:00:59

from .schema import Root
















from .schema import AggregateOp
from .schema import AndFilter
from .schema import Axis
from .schema import AxisConfig
from .schema import AxisConfigMixins
from .schema import AxisEncoding
from .schema import AxisOrient
from .schema import BOXPLOT
from .schema import BarConfig
from .schema import BaseBin
from .schema import BaseSelectionDef
from .schema import BaseSpec
from .schema import Bin
from .schema import BinTransform
from .schema import BoxPlotConfig
from .schema import BoxPlotConfigMixins
from .schema import BoxPlotDef
from .schema import BrushConfig
from .schema import CalculateTransform
from .schema import CellConfig
from .schema import CompositeMarkConfigMixins
from .schema import CompositeMarkDef
from .schema import CompositeUnitSpec
from .schema import CompositeUnitSpecAlias
from .schema import ConditionLegendFieldDef
from .schema import ConditionNumberValueDef
from .schema import ConditionOnlyNumberLegendDef
from .schema import ConditionOnlyStringLegendDef
from .schema import ConditionOnlyTextDef
from .schema import ConditionStringValueDef
from .schema import ConditionTextFieldDef
from .schema import ConditionTextValueDef
from .schema import ConditionalNumberLegendDef
from .schema import ConditionalNumberLegendFieldDef
from .schema import ConditionalNumberLegendValueDef
from .schema import ConditionalStringLegendDef
from .schema import ConditionalStringLegendFieldDef
from .schema import ConditionalStringLegendValueDef
from .schema import ConditionalTextDef
from .schema import ConditionalTextFieldDef
from .schema import ConditionalTextValueDef
from .schema import Config
from .schema import Data
from .schema import DataFormat
from .schema import DataFormatType
from .schema import DataUrlFormat
from .schema import DateTime
from .schema import ERRORBAR
from .schema import Encoding
from .schema import EncodingWithFacet
from .schema import EqualFilter
from .schema import ExtendedScheme
from .schema import Facet
from .schema import FacetFieldDef
from .schema import FacetedCompositeUnitSpecAlias
from .schema import FacetedSpec
from .schema import FacetedUnitSpec
from .schema import FieldDef
from .schema import FieldDefBase
from .schema import FilterTransform
from .schema import FontStyle
from .schema import FontWeight
from .schema import Guide
from .schema import GuideEncodingEntry
from .schema import HConcatSpec
from .schema import Header
from .schema import HorizontalAlign
from .schema import InlineData
from .schema import Interpolate
from .schema import IntervalSelection
from .schema import IntervalSelectionConfig
from .schema import LayerSpec
from .schema import LayoutSizeMixins
from .schema import Legend
from .schema import LegendConfig
from .schema import LegendEncoding
from .schema import LegendFieldDef
from .schema import LegendOrient
from .schema import LookupData
from .schema import LookupTransform
from .schema import Mark
from .schema import MarkConfig
from .schema import MarkConfigMixins
from .schema import MarkDef
from .schema import MultiSelection
from .schema import MultiSelectionConfig
from .schema import NamedData
from .schema import NonspatialResolve
from .schema import NotFilter
from .schema import NumberValueDef
from .schema import OneOfFilter
from .schema import OrFilter
from .schema import OrderFieldDef
from .schema import Orient
from .schema import PositionFieldDef
from .schema import RangeFilter
from .schema import Repeat
from .schema import RepeatRef
from .schema import RepeatSpec
from .schema import ResolveMapping
from .schema import ResolveMode
from .schema import Scale
from .schema import ScaleConfig
from .schema import ScaleFieldDef
from .schema import ScaleType
from .schema import SelectionAnd
from .schema import SelectionConfig
from .schema import SelectionDef
from .schema import SelectionDomain
from .schema import SelectionFilter
from .schema import SelectionNot
from .schema import SelectionOr
from .schema import SelectionResolution
from .schema import SingleDefChannel
from .schema import SingleSelection
from .schema import SingleSelectionConfig
from .schema import SortField
from .schema import SpatialResolve
from .schema import Spec
from .schema import StackOffset
from .schema import StringValueDef
from .schema import Summarize
from .schema import SummarizeTransform
from .schema import TextConfig
from .schema import TextFieldDef
from .schema import TextValueDef
from .schema import TickConfig
from .schema import TimeUnit
from .schema import TimeUnitTransform
from .schema import TopLevelExtendedSpec
from .schema import TopLevelFacetedSpec
from .schema import TopLevelFacetedUnitSpec
from .schema import TopLevelHConcatSpec
from .schema import TopLevelLayerSpec
from .schema import TopLevelProperties
from .schema import TopLevelRepeatSpec
from .schema import TopLevelVConcatSpec
from .schema import Transform
from .schema import Type
from .schema import UrlData
from .schema import VConcatSpec
from .schema import VLOnlyConfig
from .schema import ValueDef
from .schema import VerticalAlign
from .schema import VgAxisBase
from .schema import VgAxisConfig
from .schema import VgBinding
from .schema import VgCheckboxBinding
from .schema import VgGenericBinding
from .schema import VgLegendBase
from .schema import VgLegendConfig
from .schema import VgMarkConfig
from .schema import VgRadioBinding
from .schema import VgRangeBinding
from .schema import VgRangeScheme
from .schema import VgSelectBinding
from .schema import VgTitleConfig
from .schema import VlOnlyGuideConfig
from .channel_wrappers import ConditionalNumberLegend
from .channel_wrappers import ConditionalStringLegend
from .channel_wrappers import ConditionalText
from .channel_wrappers import FacetField
from .channel_wrappers import Field
from .channel_wrappers import OrderField
from .channel_wrappers import PositionField
from .named_channels import Color
from .named_channels import Column
from .named_channels import Detail
from .named_channels import Opacity
from .named_channels import Order
from .named_channels import Row
from .named_channels import Shape
from .named_channels import Size
from .named_channels import Text
from .named_channels import Tooltip
from .named_channels import X
from .named_channels import X2
from .named_channels import Y
from .named_channels import Y2
from .channel_collections import Encoding
from .channel_collections import EncodingWithFacet
from .channel_collections import Facet