# This file auto-generated by `generate_schema_interface.py`.
# Do not modify this file directly.

import traitlets as T


class AreaOverlay(T.Enum):
    """
    One of ['line', 'linepoint', 'none']
    """
    def __init__(self, default_value=T.Undefined, **metadata):
        super(AreaOverlay, self).__init__(['line', 'linepoint', 'none'],
                                    default_value=default_value,
                                    **metadata)