# This file auto-generated by `generate_schema_interface.py`.
# Do not modify this file directly.

import traitlets as T


class BandSize(T.Enum):
    """One of ['fit']"""
    def __init__(self, default_value=T.Undefined, **metadata):
        super(BandSize, self).__init__(['fit'],
                                    default_value=default_value,
                                    **metadata)