# This file auto-generated by `generate_schema_interface.py`.
# Do not modify this file directly.

import traitlets as T


class Type(T.Enum):
    """One of ['quantitative', 'ordinal', 'temporal', 'nominal']"""
    def __init__(self, default_value=T.Undefined, **metadata):
        super(Type, self).__init__(['quantitative', 'ordinal', 'temporal', 'nominal'],
                                    default_value=default_value,
                                    **metadata)