"""Auto-generated Python wrappers for vegalite schema"""

from .aggregateop import AggregateOp
from .axisconfig import AxisConfig
from .axisorient import AxisOrient
from .axisproperties import AxisProperties
from .binproperties import BinProperties
from .cellconfig import CellConfig
from .channeldefwithlegend import ChannelDefWithLegend
from .config import Config
from .data import Data
from .dataformat import DataFormat
from .encoding import Encoding
from .facetconfig import FacetConfig
from .facetgridconfig import FacetGridConfig
from .facetscaleconfig import FacetScaleConfig
from .fielddef import FieldDef
from .fontstyle import FontStyle
from .fontweight import FontWeight
from .horizontalalign import HorizontalAlign
from .legendconfig import LegendConfig
from .legendproperties import LegendProperties
from .mark import Mark
from .markconfig import MarkConfig
from .nicetime import NiceTime
from .orderchanneldef import OrderChannelDef
from .positionchanneldef import PositionChannelDef
from .scale import Scale
from .scaleconfig import ScaleConfig
from .scaletype import ScaleType
from .shape import Shape
from .sortfield import SortField
from .sortorder import SortOrder
from .stackoffset import StackOffset
from .timeunit import TimeUnit
from .transform import Transform
from .type import Type
from .verticalalign import VerticalAlign
from .vgformula import VgFormula
