# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject


class BinProperties(BaseObject):
    base = T.CFloat(allow_none=True, default_value=None, help="""The number base to use for automatic bin determination (default is base 10).""")
    div = T.List(T.CFloat(allow_none=True, default_value=None), allow_none=True, default_value=None, help="""Scale factors indicating allowable subdivisions.""")
    max = T.CFloat(allow_none=True, default_value=None, help="""The maximum bin value to consider.""")
    maxbins = T.CFloat(allow_none=True, default_value=None, min=2, help="""Maximum number of bins.""")
    min = T.CFloat(allow_none=True, default_value=None, help="""The minimum bin value to consider.""")
    minstep = T.CFloat(allow_none=True, default_value=None, help="""A minimum allowable step size (particularly useful for integer values).""")
    step = T.CFloat(allow_none=True, default_value=None, help="""An exact step size to use between bins.""")
    steps = T.List(T.CFloat(allow_none=True, default_value=None), allow_none=True, default_value=None, help="""An array of allowable step sizes to choose from.""")

