# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject


class BinProperties(BaseObject):
    base = T.CFloat(default_value=None, allow_none=True, help="""The number base to use for automatic bin determination (default is base 10).""")
    step = T.CFloat(default_value=None, allow_none=True, help="""An exact step size to use between bins.""")
    div = T.List(T.CFloat(default_value=None, allow_none=True), default_value=None, allow_none=True, help="""Scale factors indicating allowable subdivisions.""")
    minstep = T.CFloat(default_value=None, allow_none=True, help="""A minimum allowable step size (particularly useful for integer values).""")
    steps = T.List(T.CFloat(default_value=None, allow_none=True), default_value=None, allow_none=True, help="""An array of allowable step sizes to choose from.""")
    maxbins = T.CFloat(default_value=None, allow_none=True, min=2, help="""Maximum number of bins.""")
    max = T.CFloat(default_value=None, allow_none=True, help="""The maximum bin value to consider.""")
    min = T.CFloat(default_value=None, allow_none=True, help="""The minimum bin value to consider.""")

