# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject


class CellConfig(BaseObject):
    strokeDash = T.CFloat(default_value=None, allow_none=True)
    strokeOpacity = T.CFloat(default_value=None, allow_none=True)
    strokeDashOffset = T.CFloat(default_value=None, allow_none=True, help="""The offset (in pixels) into which to begin drawing with the stroke dash array.""")
    fill = T.Unicode(default_value=None, allow_none=True)
    stroke = T.Unicode(default_value=None, allow_none=True)
    fillOpacity = T.CFloat(default_value=None, allow_none=True)
    strokeWidth = T.CFloat(default_value=None, allow_none=True)
    height = T.CFloat(default_value=None, allow_none=True)
    clip = T.Bool(default_value=None, allow_none=True)
    width = T.CFloat(default_value=None, allow_none=True)

