# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject


class CellConfig(BaseObject):
    clip = T.Bool(allow_none=True, default_value=None)
    fill = T.Unicode(allow_none=True, default_value=None)
    fillOpacity = T.CFloat(allow_none=True, default_value=None)
    height = T.CFloat(allow_none=True, default_value=None)
    stroke = T.Unicode(allow_none=True, default_value=None)
    strokeDash = T.CFloat(allow_none=True, default_value=None)
    strokeDashOffset = T.CFloat(allow_none=True, default_value=None, help="""The offset (in pixels) into which to begin drawing with the stroke dash array.""")
    strokeOpacity = T.CFloat(allow_none=True, default_value=None)
    strokeWidth = T.CFloat(allow_none=True, default_value=None)
    width = T.CFloat(allow_none=True, default_value=None)

