# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .aggregateop import AggregateOp
from .binproperties import BinProperties
from .legendproperties import LegendProperties
from .scale import Scale
from .sortfield import SortField
from .sortorder import SortOrder
from .timeunit import TimeUnit
from .type import Type


class ChannelDefWithLegend(BaseObject):
    aggregate = AggregateOp(allow_none=True, default_value=None)
    bin = T.Union([T.Bool(allow_none=True, default_value=None), T.Instance(BinProperties, allow_none=True, default_value=None)])
    displayName = T.Unicode(allow_none=True, default_value=None)
    field = T.Unicode(allow_none=True, default_value=None)
    legend = T.Instance(LegendProperties, allow_none=True, default_value=None)
    scale = T.Instance(Scale, allow_none=True, default_value=None)
    sort = T.Union([SortOrder(allow_none=True, default_value=None), T.Instance(SortField, allow_none=True, default_value=None)])
    timeUnit = TimeUnit(allow_none=True, default_value=None)
    type = Type(allow_none=True, default_value=None)
    value = T.Union([T.Bool(allow_none=True, default_value=None), T.CFloat(allow_none=True, default_value=None), T.Unicode(allow_none=True, default_value=None)])

