# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .axisconfig import AxisConfig
from .cellconfig import CellConfig
from .facetconfig import FacetConfig
from .legendconfig import LegendConfig
from .markconfig import MarkConfig
from .scaleconfig import ScaleConfig


class Config(BaseObject):
    axis = T.Instance(AxisConfig, allow_none=True, default_value=None)
    background = T.Unicode(allow_none=True, default_value=None, help="""CSS color property to use as background of visualization.""")
    cell = T.Instance(CellConfig, allow_none=True, default_value=None)
    facet = T.Instance(FacetConfig, allow_none=True, default_value=None)
    legend = T.Instance(LegendConfig, allow_none=True, default_value=None)
    mark = T.Instance(MarkConfig, allow_none=True, default_value=None)
    numberFormat = T.Unicode(allow_none=True, default_value=None, help="""D3 Number format for axis labels and text tables.""")
    scale = T.Instance(ScaleConfig, allow_none=True, default_value=None)
    timeFormat = T.Unicode(allow_none=True, default_value=None, help="""Default datetime format for axis and legend labels.""")
    viewport = T.CFloat(allow_none=True, default_value=None, help="""The width and height of the on-screen viewport, in pixels.""")

