# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .dataformat import DataFormat


class Data(BaseObject):
    formatType = DataFormat(allow_none=True, default_value=None)
    url = T.Unicode(allow_none=True, default_value=None)
    values = T.List(T.Any(allow_none=True, default_value=None), allow_none=True, default_value=None, help="""Pass array of objects instead of a url to a file.""")

