# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject
from .dataformat import DataFormat


class Data(BaseObject):
    url = T.Unicode(default_value=None, allow_none=True)
    formatType = T.Instance(DataFormat, default_value=None, allow_none=True)
    values = T.List(T.Any(default_value=None, allow_none=True), default_value=None, allow_none=True, help="""Pass array of objects instead of a url to a file.""")

