# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .channeldefwithlegend import ChannelDefWithLegend
from .positionchanneldef import PositionChannelDef
from .fielddef import FieldDef
from .fielddef import FieldDef
from .fielddef import FieldDef
from .orderchanneldef import OrderChannelDef
from .orderchanneldef import OrderChannelDef
from .orderchanneldef import OrderChannelDef
from .orderchanneldef import OrderChannelDef
from .positionchanneldef import PositionChannelDef
from .channeldefwithlegend import ChannelDefWithLegend
from .channeldefwithlegend import ChannelDefWithLegend
from .fielddef import FieldDef
from .positionchanneldef import PositionChannelDef
from .positionchanneldef import PositionChannelDef


class Encoding(BaseObject):
    color = T.Instance(ChannelDefWithLegend, allow_none=True, default_value=None)
    column = T.Instance(PositionChannelDef, allow_none=True, default_value=None)
    detail = T.Union([T.Instance(FieldDef, allow_none=True, default_value=None), T.List(T.Instance(FieldDef, allow_none=True, default_value=None), allow_none=True, default_value=None)])
    label = T.Instance(FieldDef, allow_none=True, default_value=None)
    order = T.Union([T.Instance(OrderChannelDef, allow_none=True, default_value=None), T.List(T.Instance(OrderChannelDef, allow_none=True, default_value=None), allow_none=True, default_value=None)])
    path = T.Union([T.Instance(OrderChannelDef, allow_none=True, default_value=None), T.List(T.Instance(OrderChannelDef, allow_none=True, default_value=None), allow_none=True, default_value=None)])
    row = T.Instance(PositionChannelDef, allow_none=True, default_value=None)
    shape = T.Instance(ChannelDefWithLegend, allow_none=True, default_value=None)
    size = T.Instance(ChannelDefWithLegend, allow_none=True, default_value=None)
    text = T.Instance(FieldDef, allow_none=True, default_value=None)
    x = T.Instance(PositionChannelDef, allow_none=True, default_value=None)
    y = T.Instance(PositionChannelDef, allow_none=True, default_value=None)

