# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject
from .orderchanneldef import OrderChannelDef
from .orderchanneldef import OrderChannelDef
from .fielddef import FieldDef
from .fielddef import FieldDef
from .channeldefwithlegend import ChannelDefWithLegend
from .orderchanneldef import OrderChannelDef
from .orderchanneldef import OrderChannelDef
from .fielddef import FieldDef
from .positionchanneldef import PositionChannelDef
from .channeldefwithlegend import ChannelDefWithLegend
from .positionchanneldef import PositionChannelDef
from .positionchanneldef import PositionChannelDef
from .fielddef import FieldDef
from .channeldefwithlegend import ChannelDefWithLegend
from .positionchanneldef import PositionChannelDef


class Encoding(BaseObject):
    order = T.Union([T.Instance(OrderChannelDef, default_value=None, allow_none=True), T.List(T.Instance(OrderChannelDef, default_value=None, allow_none=True), default_value=None, allow_none=True)])
    detail = T.Union([T.Instance(FieldDef, default_value=None, allow_none=True), T.List(T.Instance(FieldDef, default_value=None, allow_none=True), default_value=None, allow_none=True)])
    size = T.Instance(ChannelDefWithLegend, default_value=None, allow_none=True)
    path = T.Union([T.Instance(OrderChannelDef, default_value=None, allow_none=True), T.List(T.Instance(OrderChannelDef, default_value=None, allow_none=True), default_value=None, allow_none=True)])
    label = T.Instance(FieldDef, default_value=None, allow_none=True)
    column = T.Instance(PositionChannelDef, default_value=None, allow_none=True)
    shape = T.Instance(ChannelDefWithLegend, default_value=None, allow_none=True)
    x = T.Instance(PositionChannelDef, default_value=None, allow_none=True)
    y = T.Instance(PositionChannelDef, default_value=None, allow_none=True)
    text = T.Instance(FieldDef, default_value=None, allow_none=True)
    color = T.Instance(ChannelDefWithLegend, default_value=None, allow_none=True)
    row = T.Instance(PositionChannelDef, default_value=None, allow_none=True)

