# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject


class FacetScaleConfig(BaseObject):
    padding = T.CFloat(default_value=None, allow_none=True)
    round = T.Bool(default_value=None, allow_none=True)

