# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject


class FacetGridConfig(BaseObject):
    offset = T.CFloat(default_value=None, allow_none=True)
    color = T.Unicode(default_value=None, allow_none=True)
    opacity = T.CFloat(default_value=None, allow_none=True)

