# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject


class FacetGridConfig(BaseObject):
    color = T.Unicode(allow_none=True, default_value=None)
    offset = T.CFloat(allow_none=True, default_value=None)
    opacity = T.CFloat(allow_none=True, default_value=None)

