# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject


class FacetScaleConfig(BaseObject):
    padding = T.CFloat(allow_none=True, default_value=None)
    round = T.Bool(allow_none=True, default_value=None)

