# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .axisconfig import AxisConfig
from .cellconfig import CellConfig
from .facetgridconfig import FacetGridConfig
from .facetscaleconfig import FacetScaleConfig


class FacetConfig(BaseObject):
    axis = T.Instance(AxisConfig, allow_none=True, default_value=None)
    cell = T.Instance(CellConfig, allow_none=True, default_value=None)
    grid = T.Instance(FacetGridConfig, allow_none=True, default_value=None)
    scale = T.Instance(FacetScaleConfig, allow_none=True, default_value=None)

