# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .aggregateop import AggregateOp
from .binproperties import BinProperties
from .timeunit import TimeUnit
from .type import Type


class FieldDef(BaseObject):
    aggregate = AggregateOp(allow_none=True, default_value=None)
    bin = T.Union([T.Bool(allow_none=True, default_value=None), T.Instance(BinProperties, allow_none=True, default_value=None)])
    displayName = T.Unicode(allow_none=True, default_value=None)
    field = T.Unicode(allow_none=True, default_value=None)
    timeUnit = TimeUnit(allow_none=True, default_value=None)
    type = Type(allow_none=True, default_value=None)
    value = T.Union([T.CFloat(allow_none=True, default_value=None), T.Unicode(allow_none=True, default_value=None), T.Bool(allow_none=True, default_value=None)])

