# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T


class FontStyle(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(FontStyle, self).__init__(['normal', 'italic', ],
                                       default_value=default_value,
                                       **metadata)