# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class FontWeight(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(FontWeight, self).__init__(['normal', 'bold'],
                                    default_value=default_value,
                                    **metadata)
