# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class HorizontalAlign(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(HorizontalAlign, self).__init__(['left', 'right', 'center'],
                                    default_value=default_value,
                                    **metadata)
