# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject


class LegendProperties(BaseObject):
    format = T.Unicode(default_value=None, allow_none=True, help="""An optional formatting pattern for legend labels.""")
    properties = T.Any(default_value=None, allow_none=True, help="""Optional mark property definitions for custom legend styling.""")
    values = T.List(T.Any(default_value=None, allow_none=True), default_value=None, allow_none=True, help="""Explicitly set the visible legend values.""")
    title = T.Unicode(default_value=None, allow_none=True, help="""A title for the legend.""")
    orient = T.Unicode(default_value=None, allow_none=True, help="""The orientation of the legend.""")
    shortTimeLabels = T.Bool(default_value=None, allow_none=True, help="""Whether month names and weekday names should be abbreviated.""")

