# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class Mark(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(Mark, self).__init__(['area', 'bar', 'line', 'point', 'text', 'tick', 'circle', 'square'],
                                    default_value=default_value,
                                    **metadata)
