# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class NiceTime(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(NiceTime, self).__init__(['second', 'minute', 'hour', 'day', 'week', 'month', 'year'],
                                    default_value=default_value,
                                    **metadata)
