# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
from .aggregateop import AggregateOp
from .sortorder import SortOrder


class SortField(BaseObject):
    field = T.Unicode(allow_none=True, default_value=None, help="""The field name to aggregate over.""")
    op = AggregateOp(allow_none=True, default_value=None, help="""The sort aggregation operator.""")
    order = SortOrder(allow_none=True, default_value=None)

