# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject
from .sortorder import SortOrder
from .aggregateop import AggregateOp


class SortField(BaseObject):
    order = T.Instance(SortOrder, default_value=None, allow_none=True)
    field = T.Unicode(default_value=None, allow_none=True, help="""The field name to aggregate over.""")
    op = T.Instance(AggregateOp, default_value=None, allow_none=True, help="""The sort aggregation operator.""")

