# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class SortOrder(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(SortOrder, self).__init__(['ascending', 'descending', 'none'],
                                    default_value=default_value,
                                    **metadata)
