# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class StackOffset(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(StackOffset, self).__init__(['zero', 'center', 'normalize', 'none'],
                                    default_value=default_value,
                                    **metadata)
