# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class TimeUnit(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(TimeUnit, self).__init__(['year', 'month', 'day', 'date', 'hours', 'minutes', 'seconds', 'milliseconds', 'yearmonth', 'yearmonthday', 'yearmonthdate', 'yearday', 'yeardate', 'yearmonthdayhours', 'yearmonthdayhoursminutes', 'yearmonthdayhoursminutesseconds', 'hoursminutes', 'hoursminutesseconds', 'minutesseconds', 'secondsmilliseconds'],
                                    default_value=default_value,
                                    **metadata)
