# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject
from .vgformula import VgFormula


class Transform(BaseObject):
    calculate = T.List(T.Instance(VgFormula, default_value=None, allow_none=True), default_value=None, allow_none=True, help="""Calculate new field(s) using the provided expresssion(s).""")
    filter = T.Unicode(default_value=None, allow_none=True, help="""A string containing the filter Vega expression.""")
    filterNull = T.Bool(default_value=None, allow_none=True, help="""Filter null values from the data.""")

