# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class Type(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(Type, self).__init__(['quantitative', 'ordinal', 'temporal', 'nominal'],
                                    default_value=default_value,
                                    **metadata)
