# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T


class VerticalAlign(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super(VerticalAlign, self).__init__(['top', 'middle', 'bottom'],
                                    default_value=default_value,
                                    **metadata)
