# This file auto-generated by altair.schema.parser.write_files().
# do not modify directly.

import traitlets as T
from ..baseobject import BaseObject


class VgFormula(BaseObject):
    field = T.Unicode(default_value=None, allow_none=True, help="""The field in which to store the computed formula value.""")
    expr = T.Unicode(default_value=None, allow_none=True, help="""A string containing an expression for the formula.""")

