# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject


class VgFormula(BaseObject):
    expr = T.Unicode(allow_none=True, default_value=None, help="""A string containing an expression for the formula.""")
    field = T.Unicode(allow_none=True, default_value=None, help="""The field in which to store the computed formula value.""")

