# This file auto-generated by `generate_schema_interface.py`.
# Do not modify this file directly.

{% for import in imports -%}
from .{{ import.lower() }} import {{ import }}
{% endfor %}

{% for channel in channels -%}
class {{ channel.name }}({{ channel.base }}):
    channel_name = '{{ channel.name.lower() }}'


{% endfor -%}

CHANNEL_CLASSES = {
    {%- for channel in channels %}
    '{{ channel.name.lower() }}': {{ channel.name }},
    {%- endfor %}
}

CHANNEL_NAMES = list(CHANNEL_CLASSES.keys())
