# This file auto-generated by `generate_schema_interface.py`.
# Do not modify this file directly.

{% for object in objects %}{% for import in object.imports %}
{%- set comma = joiner(", ") %}
from {{ import.module }} import {% for name in import.names %}{{ comma() }}{{ name }}{% endfor %}
{%- endfor %}{% endfor %}


{% for object in objects -%}
class {{ object.name }}({{ object.base.name }}):
    channel_name = '{{ object.name.lower() }}'


{% endfor -%}

CHANNEL_CLASSES = {
    {%- for object in objects %}
    '{{ object.name.lower() }}': {{ object.name }},
    {%- endfor %}
}

CHANNEL_NAMES = list(CHANNEL_CLASSES.keys())
