# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T


class {{ cls.name }}(T.Enum):
    def __init__(self, default_value=T.Undefined, **metadata):
        super({{ cls.name }}, self).__init__([{% for option in cls.enum %}'{{ option }}', {% endfor %}],
                                       default_value=default_value,
                                       **metadata)
