# This file auto-generated by `generate_schema_interface.py`.
# Do not modify this file directly.

{% for import_statement in objects|merge_imports -%}
  {{ import_statement }}
{% endfor %}

{% for object in objects -%}
class {{ object.name }}({{ object.base.name }}):
    pass


{% endfor -%}

CHANNEL_CLASSES = {
    {%- for object in objects %}
    '{{ object.name.lower() }}': {{ object.name }},
    {%- endfor %}
}

CHANNEL_NAMES = list(CHANNEL_CLASSES.keys())
