# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.

import traitlets as T
from ..baseobject import BaseObject
{% for import in cls.imports %}from .{{ import.lower() }} import {{ import }}
{% endfor %}

class {{ cls.name }}(BaseObject):
    """{{ cls.short_description }}
    {{ cls.long_description }}
    Attributes
    ----------
    {% for attr in cls.attributes %}{{ attr.name }}: {{ attr.trait_descr}}
        {{ attr.short_description }}
    {% endfor %}"""
    {% for attr in cls.attributes %}{{ attr.name }} = {{ attr.trait_fulldef }}
    {% endfor %}

    def __init__(self, {% for attr in cls.attributes %}{{ attr.name }}=None, {% endfor %}**kwargs):
        kwds = dict({% for attr in cls.attributes %}{{ attr.name }}={{ attr.name }}, {% endfor %})
        kwargs.update({k:v for k, v in kwds.items() if v is not None})
        super({{ cls.name }}, self).__init__(**kwargs)
