# This file auto-generated by `_schema_parser.py`.
# Do not modify this file directly.
"""
Test that all auto-generated schema objects can be instatiated.
"""

from .. import *

{% for cls in classes %}
def test_instantiate_{{ cls.name }}():
    obj = {{ cls.name }}()

{% endfor %}
