name: docbuild

on:
  push:
    paths: &docbuild_paths
      - ".github/workflows/docbuild.yml"
      - "doc/**"
      - "pyproject.toml"
      - "tests/examples_*/**"
      - "tools/**"
      - "uv.lock"
  pull_request:
    paths: *docbuild_paths

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml
    - name: Install dependencies
      run: uv sync --all-extras
    - name: Build docs
      run: |
        mkdir -p doc/_images
        uv run sphinx-build -b html -d doc/_build/doctrees doc doc/_build/html
    - name: Run doctests
      run: |
        uv run sphinx-build -b doctest -d doc/_build/doctrees doc doc/_build/doctest

        
